# RSS Agent Configuration

agents:
  - name: rss_agent
    role: RSS Feed Fetcher
    goal: Fetch content from RSS feeds and extract relevant information
    backstory: You are a specialized agent designed to retrieve and parse RSS feeds efficiently.
    verbose: True
    allow_delegation: False

tasks:
  - description: Fetch and parse RSS feed content
    expected_output: RSS feed content and metadata
    agent: rss_agent
    max_inter: 1
    human_input: False

model:
  model_api_key: ""
  model_name: "gemini-2.0-flash"
  model_provider: "google"
  model_max_tokens: 2048
  model_endpoint: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

crewai_config:
  memory: False


rss_config:
  urls:
    - name: "Google News"
      url: "https://news.google.com/rss"
    - name: "BBC News"
      url: "http://feeds.bbci.co.uk/news/world/rss.xml"
    - name: "纽约时报"
      url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml"
    - name: "36氪"
      url: "https://36kr.com/feed"
    - name: "少数派"
      url: "https://sspai.com/feed"
    - name: "InfoQ"
      url: "https://www.infoq.cn/feed"
    - name: "Hacker News"
      url: "https://news.ycombinator.com/rss"
  default_url: "https://news.google.com/rss"
  timeout: 30
  max_items: 20  # 减少每个源的条目数，避免文件过大
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  max_retries: 2

categorization_config:
  enabled: true
  max_categories: 7
  min_categories: 4
  output_format: markdown
  generate_individual_files: true  # 是否同时生成每个源的单独文件
